services:
  postgres:
    image: postgres:15
    container_name: vitrine_db
    environment:
      POSTGRES_DB: vitrine
      POSTGRES_USER: vitrine_user
      POSTGRES_PASSWORD: vitrine_pass
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: vitrine_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      TZ: Europe/Paris
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build:
      context: ./frontend
    container_name: vitrine_frontend
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  postgres_data: