CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE product_images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_path VARCHAR(255),
    product_id BIGINT,
    CONSTRAINT pk_productimages PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(2000),
    price       DECIMAL                                 NOT NULL,
    category_id BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    id_roles INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE actualites
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    description     VARCHAR(255),
    CONSTRAINT uq_actualites_title UNIQUE (title)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCTIMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ID_ROLES FOREIGN KEY (id_roles) REFERENCES roles (id);

INSERT INTO roles (libelle)
SELECT 'ADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE libelle = 'ADMIN'
);

INSERT INTO users (username, password, id_roles)
SELECT
    'admin',
    '$2a$10$YiM3lmvkJrjrAhTwEqHYtOHe68uKNqCNyIIhqCPiXfLp7RHrWZvBu',
    (SELECT id FROM roles WHERE libelle = 'ADMIN')
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'admin'
);