spring.application.name=vitrine-api

spring.datasource.url=jdbc:postgresql://vitrine-postgres:5432/vitrine
spring.datasource.username=vitrine_user
spring.datasource.password=vitrine_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

spring.jpa.hibernate.ddl-auto=none

app.jwt.secret=kwmOI7QhxROpaOCi9uGHOBEWGTOpLME8v5t9XRk1CMooVmqNFoZJtevrRb0KGCXB3UeDNMlILSYlejawkhkMxh

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true